# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 23:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_number', models.IntegerField(verbose_name='Permit Number')),
                ('master_use_permit', models.IntegerField(blank=True, verbose_name='Master Use Permit')),
                ('action_type', models.CharField(blank=True, max_length=25, verbose_name='Action Type')),
                ('address', models.CharField(blank=True, max_length=50, verbose_name='Address')),
                ('applicant_name', models.CharField(blank=True, max_length=24, verbose_name='Applicant Name')),
                ('application_date', models.DateTimeField(blank=True, verbose_name='Application Date')),
                ('issue_date', models.DateTimeField(blank=True, verbose_name='Issue Date')),
                ('final_date', models.DateTimeField(blank=True, verbose_name='Final Date')),
                ('experation_date', models.DateTimeField(blank=True, verbose_name='Experation Date')),
                ('category', models.CharField(blank=True, max_length=24, verbose_name='Category')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('latitude', models.FloatField(blank=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, verbose_name='Longitude')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('permit_type', models.CharField(blank=True, max_length=24, verbose_name='Type')),
                ('status', models.CharField(blank=True, max_length=24, verbose_name='Status')),
                ('value', models.IntegerField(blank=True, verbose_name='Value')),
                ('work_type', models.CharField(blank=True, max_length=24, verbose_name='Work Type')),
                ('contractor', models.CharField(blank=True, max_length=55, verbose_name='Contractor')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list', related_query_name='permits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('application_date',),
            },
        ),
    ]
