# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_auto_20161029_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permit',
            name='applicant_name',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='Applicant Name'),
        ),
        migrations.AlterField(
            model_name='permit',
            name='application_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Application Date'),
        ),
        migrations.AlterField(
            model_name='permit',
            name='experation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Experation Date'),
        ),
        migrations.AlterField(
            model_name='permit',
            name='final_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Final Date'),
        ),
        migrations.AlterField(
            model_name='permit',
            name='issue_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Issue Date'),
        ),
        migrations.AlterField(
            model_name='permit',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='permit',
            name='value',
            field=models.IntegerField(blank=True, null=True, verbose_name='Value'),
        ),
    ]
