# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_auto_20161029_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permit',
            name='permit_number',
            field=models.IntegerField(unique=True, verbose_name='Permit Number'),
        ),
    ]
