# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_auto_20161029_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='permit',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permit',
            name='date_modified',
            field=models.DateField(auto_now=True, verbose_name='Date Modified'),
        ),
    ]
