# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0006_auto_20161029_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permit',
            name='status',
            field=models.CharField(blank=True, max_length=32, verbose_name='Status'),
        ),
    ]
