# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0008_auto_20161029_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permit',
            name='action_type',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Action Type'),
        ),
        migrations.AlterField(
            model_name='permit',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='permit',
            name='category',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='permit',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='permit',
            name='permit_type',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='permit',
            name='status',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='permit',
            name='work_type',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='Work Type'),
        ),
    ]
