# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0011_auto_20161030_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permit',
            name='contractor',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Contractor'),
        ),
    ]
