# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0013_auto_20161030_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permit',
            name='value',
            field=models.FloatField(blank=True, null=True, verbose_name='Value'),
        ),
    ]
