# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permit_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permituser',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='permituser',
            name='location',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='permituser',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
    ]
